name: home_food_delivery
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  form_validator: ^1.0.2
  mysql1: ^0.19.2
  flappy_search_bar: 1.4.1
  kiwi: ^4.0.2
  material_floating_search_bar: ^0.3.6
  shared_preferences: ^2.0.13
  google_maps_flutter: ^2.1.2
  geocoding: ^2.0.2
  http: ^0.13.4
  geolocator: ^8.2.0
  flutter_spinkit: ^5.1.0
  date_time_picker: ^2.1.0
  google_fonts: ^2.3.0
  flex_color_scheme: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
